complete -f -c elm-repl -s c -l compiler -a FILE -d 'Provide a path to a specific version of elm-make.'
complete -f -c elm-repl -s i -l interpreter -a node -d 'Provide a path to a specific JavaScript interpreter'
complete -f -c elm-repl -s h -l help -d 'Display help message'
complete -f -c elm-repl -s v -l version -d 'Print version information'
complete -f -c elm-repl -l 'numeric-version' -d 'Print just the version number'
