complete -f -c elm-reactor -s a -l address -a 0.0.0.0 -d 'set the address of the server'
complete -f -c elm-reactor -s p -l port -a 8000 -d 'set the port of the reactor'
complete -f -c elm-reactor -s h -l help -d 'Display help message'
complete -f -c elm-reactor -s v -l version -d 'Print version information'
complete -f -c elm-reactor -l 'numeric-version' -d 'Print just the version number'
